### ISSUE TITLE
Inconsistent API names

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-monitoring#2]
The monitoring API currently requires the following API names:
- **organizational-units** but the name of the repository is ewp-specs-api-ounits, so it should require just **ounits**
- **simple-course-replication** but the name of the repository is ewp-specs-api-course-replication, so it should require just **course-replication**

**Comment by MBala98** [comment]
Hey Jiri, the reason why the names are "organizational-units" and "simple-course-replication" is because these are the values in manifest files of these APIs under "name" element. 

The manifest are the actual part of EWP network and the source of truth. That's what the Registry uses and that's what's available in the Catalogue to EWP nodes. Repository names in GitHub are not part of any specification and while it's useful that in most cases the suffix of the repository is API name, it's not a hard requirement. The repository name definitely should not take precedence over the Manifest. One simple way to think about it is: When you are searching for all nodes that implement "Organizational Units" API, you are searching for it by "organizational-units" value in the Catalogue, not "ounits". That's why the value to pass in the Monitoring API is also "organizational-units".

**Comment by jiripetrzelka** [comment]
OK, thank you for the clarification.
